### ISSUE TITLE
Chef 12.6.0 -  property group is declared in both directory[/etc/sv/chef-client/log] and #<Chef::Provider::RunitService:0x0000000da390a0>. Use new_resource.group instead.

### ISSUE THREAD

**Issue by petecheslock** [hw-cookbooks/runit#174]
Seeing this warn in chef 12.6.0 and runit cookbook version > 1.7.4

```
 * runit_service[chef-client] action enable[2015-12-30T21:11:49+00:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:58:in `block (2 levels) in <class:RunitService>': property group is declared in both directo
ry[/etc/sv/chef-client] and #<Chef::Provider::RunitService:0x0000000da390a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:58:in `block (2 levels) in <class:RunitService>'
[2015-12-30T21:11:49+00:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:66:in `block (2 levels) in <class:RunitService>': property group is declared in both template[/etc/sv/chef-client/run] and #<Chef::Provi
der::RunitService:0x0000000da390a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:66:in `block (2 levels) in <class:RunitService>'
[2015-12-30T21:11:49+00:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:78:in `block (2 levels) in <class:RunitService>': property group is declared in both directory[/etc/sv/chef-client/log] and #<Chef::Prov
ider::RunitService:0x0000000da390a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:78:in `block (2 levels) in <class:RunitService>'
[2015-12-30T21:11:49+00:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:85:in `block (2 levels) in <class:RunitService>': property group is declared in both directory[/etc/sv/chef-client/log/main] and #<Chef:
:Provider::RunitService:0x0000000da390a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:85:in `block (2 levels) in <class:RunitService>'
[2015-12-30T21:11:49+00:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:93:in `block (2 levels) in <class:RunitService>': property group is declared in both directory[/var/log/chef-client] and #<Chef::Provide
r::RunitService:0x0000000da390a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:93:in `block (2 levels) in <class:RunitService>'
[2015-12-30T21:11:49+00:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:101:in `block (2 levels) in <class:RunitService>': property group is declared in both template[/etc/sv/chef-client/log/config] and #<Che
f::Provider::RunitService:0x0000000da390a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:101:in `block (2 levels) in <class:RunitService>'
[2015-12-30T21:11:49+00:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:124:in `block (2 levels) in <class:RunitService>': property group is declared in both template[/etc/sv/chef-client/log/run] and #<Chef::
Provider::RunitService:0x0000000da390a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:124:in `block (2 levels) in <class:RunitService>'
[2015-12-30T21:11:49+00:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:138:in `block (2 levels) in <class:RunitService>': property group is declared in both directory[/etc/sv/chef-client/env] and #<Chef::Pro
vider::RunitService:0x0000000da390a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:138:in `block (2 levels) in <class:RunitService>'
[2015-12-30T21:11:49+00:00] WARN: /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:186:in `block (2 levels) in <class:RunitService>': property group is declared in both directory[/etc/sv/chef-client/control] and #<Chef:
:Provider::RunitService:0x0000000da390a0>. Use new_resource.group instead. At /var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:186:in `block (2 levels) in <class:RunitService>'
```

**Comment by petecheslock** [comment]
Granted this is a WARN only - not seeing usage issues from this as far as i can see

**Comment by lamont-granquist** [comment]
https://github.com/chef/chef/issues/4334

**Comment by luckymike** [comment]
Closing per the issue @lamont-granquist referenced.
